---
- name: Download K3s binary
  ansible.builtin.get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: "{{ k3s_binary_path }}"
    mode: '0755'

- name: Create K3s service directory
  ansible.builtin.file:
    path: /etc/systemd/system/k3s.service.d
    state: directory
    mode: '0755'

- name: Create modprobe wrapper
  ansible.builtin.copy:
    dest: /usr/local/bin/modprobe
    mode: '0755'
    content: |
      #!/bin/sh
      # No-op wrapper for WSL environments
      exit 0

- name: Create k3s config file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: '0644'