---
- name: Install EPEL repository
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Check Docker installation
  ansible.builtin.command: docker --version
  register: docker_check
  changed_when: false
  failed_when: false

- name: Fail if Docker is not installed
  ansible.builtin.fail:
    msg: "Docker is not installed or not running. Please ensure Docker Desktop is running in Windows and WSL integration is enabled."
  when: docker_check.rc != 0

- name: Install required packages
  ansible.builtin.dnf:
    name: 
      - git
      - python3-pip
    state: present

- name: Install required Python packages
  ansible.builtin.pip:
    name:
      - kubernetes>=12.0.0
      - openshift>=0.12.0
    state: present

- name: Check if K3s binary exists
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Create kubectl symlink to K3s
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link
    force: yes
  when: k3s_binary.stat.exists

- name: Verify kubectl installation
  ansible.builtin.command: kubectl version --client
  register: kubectl_check
  changed_when: false
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: Fail if kubectl is not configured
  ansible.builtin.fail:
    msg: "kubectl is not properly configured. Please ensure your Kubernetes cluster is running and accessible."
  when: kubectl_check.rc != 0