---
- name: Install EPEL repository
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Check Docker installation
  ansible.builtin.command: docker --version
  register: docker_check
  changed_when: false
  failed_when: false

- name: Fail if Docker is not installed
  ansible.builtin.fail:
    msg: "Docker is not installed or not running. Please ensure Docker Desktop is running in Windows and WSL integration is enabled."
  when: docker_check.rc != 0

- name: Install required packages
  ansible.builtin.dnf:
    name: 
      - yum-utils
      - python3-pip
      - git
      - iptables
      - iptables-services
      - kmod
      - kmod-libs
    state: present

- name: Install required Python packages
  ansible.builtin.pip:
    name:
      - kubernetes>=12.0.0
      - openshift>=0.12.0
    state: present

- name: Verify kubectl installation
  ansible.builtin.command: kubectl version --client
  register: kubectl_check
  changed_when: false
  failed_when: false

- name: Fail if kubectl is not available
  ansible.builtin.fail:
    msg: "kubectl is not installed or not in PATH. Please ensure K3s/kubectl is properly installed."
  when: kubectl_check.rc != 0

- name: Enable iptables service
  ansible.builtin.systemd:
    name: iptables
    state: started
    enabled: true